# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTags',
            new_name='UserTag',
        ),
    ]
