# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20160517_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
