# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_subscriptionactivation_unsubscriptionactivation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionActivation',
            new_name='EmailVerification',
        ),
        migrations.RemoveField(
            model_name='unsubscriptionactivation',
            name='user',
        ),
        migrations.RenameField(
            model_name='emailverification',
            old_name='subscribe_key',
            new_name='key',
        ),
        migrations.DeleteModel(
            name='UnsubscriptionActivation',
        ),
    ]
