# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_auto_20160519_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
